# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Spice Gears Robot Code Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2-beta
      - name: FRC Build & Test
        uses: ewpratten/FRC-actions@v1
        with:
          build_mode: "all"
